"""Manifest + dataset card for the annotation pipeline output."""

from __future__ import annotations

import json
import os
from collections import Counter
from typing import Iterable

from .models import Segment
from ..models import ItemState


def write_segments_jsonl(segments: Iterable[Segment], path: str) -> int:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    n = 0
    with open(path, "w", encoding="utf-8") as fh:
        for seg in segments:
            fh.write(json.dumps(seg.to_dict(), ensure_ascii=False) + "\n")
            n += 1
    return n


def summarise(segments: list[Segment]) -> dict:
    states = Counter(s.state.value for s in segments)
    accepted = [s for s in segments if s.state == ItemState.ACCEPTED]
    total_dur = sum(s.duration_s for s in segments)
    accepted_dur = sum(s.duration_s for s in accepted)
    return {
        "segments": len(segments),
        "by_state": dict(states),
        "speakers": len({s.speaker for s in segments}),
        "total_seconds": round(total_dur, 2),
        "accepted_seconds": round(accepted_dur, 2),
        "accepted_hours": round(accepted_dur / 3600.0, 4),
    }


def write_dataset_card(segments: list[Segment], path: str,
                       wer: dict | None = None,
                       name: str = "Go-on Lab Annotated Corpus") -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    s = summarise(segments)
    lines = [
        f"# {name} — Dataset Card", "",
        "Auto-generated by the annotation (pseudo-labeling) pipeline.",
        "Labels are machine-generated; see the measured error rate below.", "",
        "## Statistics", "",
        f"- Segments: {s['segments']}",
        f"- Accepted: {s['by_state'].get('accepted', 0)}",
        f"- In review: {s['by_state'].get('review', 0)}",
        f"- Rejected: {s['by_state'].get('rejected', 0)}",
        f"- Distinct speakers: {s['speakers']}",
        f"- Accepted audio: {s['accepted_hours']} hours "
        f"({s['accepted_seconds']} s)",
        "",
        "## Measured label quality", "",
    ]
    if wer:
        lines += _quality_lines(wer)
    else:
        lines.append("- Error rate not yet measured. Sample with "
                     "`corpus.annotation.evaluation.stratified_sample`, verify via "
                     "a review sheet (`review_sheet`), then "
                     "`measure_error_rates` and regenerate this card.")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def _quality_lines(q: dict) -> list[str]:
    """Render either the rich ErrorRateResult dict or the legacy WER dict."""
    lines = [f"- Sampled segments hand-verified: {q.get('n_segments', '?')}"]
    if "cer" in q:  # rich ErrorRateResult
        wci = q.get("wer_ci95") or []
        cci = q.get("cer_ci95") or []
        wci_s = f" (95% CI {wci[0]:.1%}–{wci[1]:.1%})" if len(wci) == 2 else ""
        cci_s = f" (95% CI {cci[0]:.1%}–{cci[1]:.1%})" if len(cci) == 2 else ""
        lines += [
            f"- **Word Error Rate (WER): {q['wer']:.1%}**{wci_s} "
            f"({q.get('total_word_errors','?')}/{q.get('total_words','?')} words)",
            f"- **Character Error Rate (CER): {q['cer']:.1%}**{cci_s} "
            f"({q.get('total_char_errors','?')}/{q.get('total_chars','?')} chars)",
        ]
        by_band = q.get("by_band") or {}
        if by_band:
            lines += ["", "### Error rate by ASR confidence band", "",
                      "| band | n | WER | CER |", "|---|---|---|---|"]
            for band, b in by_band.items():
                lines.append(f"| {band} | {b['n']} | {b['wer']:.1%} | {b['cer']:.1%} |")
    else:  # legacy WER-only dict
        lines.append(
            f"- **Word Error Rate (WER): {q['wer']:.1%}** "
            f"({q.get('total_errors','?')}/{q.get('total_words','?')} words)")
    return lines


def export(segments: list[Segment], out_dir: str, wer: dict | None = None,
           accepted_only: bool = False) -> dict:
    sel = ([s for s in segments if s.state == ItemState.ACCEPTED]
           if accepted_only else list(segments))
    write_segments_jsonl(sel, os.path.join(out_dir, "segments.jsonl"))
    write_dataset_card(sel, os.path.join(out_dir, "DATASET_CARD.md"), wer)
    return summarise(sel)
