"""Manifest + dataset card for the annotation pipeline output."""

from __future__ import annotations

import json
import os
from collections import Counter
from typing import Iterable

from .models import Segment
from ..models import ItemState


def write_segments_jsonl(segments: Iterable[Segment], path: str) -> int:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    n = 0
    with open(path, "w", encoding="utf-8") as fh:
        for seg in segments:
            fh.write(json.dumps(seg.to_dict(), ensure_ascii=False) + "\n")
            n += 1
    return n


def summarise(segments: list[Segment]) -> dict:
    states = Counter(s.state.value for s in segments)
    accepted = [s for s in segments if s.state == ItemState.ACCEPTED]
    total_dur = sum(s.duration_s for s in segments)
    accepted_dur = sum(s.duration_s for s in accepted)
    return {
        "segments": len(segments),
        "by_state": dict(states),
        "speakers": len({s.speaker for s in segments}),
        "total_seconds": round(total_dur, 2),
        "accepted_seconds": round(accepted_dur, 2),
        "accepted_hours": round(accepted_dur / 3600.0, 4),
    }


def write_dataset_card(segments: list[Segment], path: str,
                       wer: dict | None = None,
                       name: str = "Go-on Lab Annotated Corpus") -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    s = summarise(segments)
    lines = [
        f"# {name} — Dataset Card", "",
        "Auto-generated by the annotation (pseudo-labeling) pipeline.",
        "Labels are machine-generated; see the measured error rate below.", "",
        "## Statistics", "",
        f"- Segments: {s['segments']}",
        f"- Accepted: {s['by_state'].get('accepted', 0)}",
        f"- In review: {s['by_state'].get('review', 0)}",
        f"- Rejected: {s['by_state'].get('rejected', 0)}",
        f"- Distinct speakers: {s['speakers']}",
        f"- Accepted audio: {s['accepted_hours']} hours "
        f"({s['accepted_seconds']} s)",
        "",
        "## Measured label quality", "",
    ]
    if wer:
        lines += [
            f"- Sampled segments hand-verified: {wer['n_segments']}",
            f"- **Word Error Rate (WER): {wer['wer']:.1%}** "
            f"({wer['total_errors']}/{wer['total_words']} words)",
        ]
    else:
        lines.append("- WER not yet measured. Hand-verify a random sample with "
                     "`corpus.annotation.evaluation` and regenerate this card.")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def export(segments: list[Segment], out_dir: str, wer: dict | None = None,
           accepted_only: bool = False) -> dict:
    sel = ([s for s in segments if s.state == ItemState.ACCEPTED]
           if accepted_only else list(segments))
    write_segments_jsonl(sel, os.path.join(out_dir, "segments.jsonl"))
    write_dataset_card(sel, os.path.join(out_dir, "DATASET_CARD.md"), wer)
    return summarise(sel)
