"""Manifest, dataset card and on-disk layout for processed items.

The manifest is the index a researcher or buyer reads. It records, per item, the
decision, key QC metrics, licence and whether the item is sellable — so a
commercial export can be produced deterministically and audited.
"""

from __future__ import annotations

import csv
import json
import os
from collections import Counter
from typing import Iterable

from ..models import CorpusItem, ItemState


def write_jsonl(items: Iterable[CorpusItem], path: str) -> int:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    n = 0
    with open(path, "w", encoding="utf-8") as fh:
        for item in items:
            fh.write(json.dumps(item.to_dict(), ensure_ascii=False) + "\n")
            n += 1
    return n


def write_csv_manifest(items: Iterable[CorpusItem], path: str) -> int:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    fields = ["recording_id", "speaker_id", "prompt_id", "language", "state",
              "sellable", "duration_s", "snr_db", "cer", "audio_path"]
    n = 0
    with open(path, "w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        for it in items:
            writer.writerow({
                "recording_id": it.recording.recording_id,
                "speaker_id": it.recording.speaker_id,
                "prompt_id": it.prompt.prompt_id,
                "language": it.prompt.language,
                "state": it.state.value,
                "sellable": it.is_sellable(),
                "duration_s": it.qc_metrics.get("duration_s"),
                "snr_db": it.qc_metrics.get("snr_db"),
                "cer": it.verification.get("cer"),
                "audio_path": it.recording.audio_path,
            })
            n += 1
    return n


def summarise(items: list[CorpusItem]) -> dict:
    states = Counter(it.state.value for it in items)
    langs = Counter(it.prompt.language for it in items)
    sellable = sum(1 for it in items if it.is_sellable())
    accepted = [it for it in items if it.state == ItemState.ACCEPTED]
    total_dur = sum(it.qc_metrics.get("duration_s") or 0.0 for it in accepted)
    return {
        "total": len(items),
        "by_state": dict(states),
        "by_language": dict(langs),
        "sellable": sellable,
        "accepted_hours": round(total_dur / 3600.0, 4),
        "speakers": len({it.recording.speaker_id for it in items}),
    }


def write_dataset_card(items: list[CorpusItem], path: str,
                       name: str = "Go-on Lab Corpus") -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    s = summarise(items)
    lines = [
        f"# {name} — Dataset Card", "",
        "Auto-generated by the corpus backend. See docs/LICENSING.md for the",
        "consent/licensing model that governs commercial use.", "",
        "## Statistics", "",
        f"- Total items: {s['total']}",
        f"- Accepted: {s['by_state'].get('accepted', 0)}",
        f"- In review: {s['by_state'].get('review', 0)}",
        f"- Rejected: {s['by_state'].get('rejected', 0)}",
        f"- **Sellable items: {s['sellable']}**",
        f"- Accepted audio: {s['accepted_hours']} hours",
        f"- Distinct speakers: {s['speakers']}",
        f"- Languages: {', '.join(f'{k} ({v})' for k, v in s['by_language'].items())}",
        "",
    ]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def export_corpus(items: list[CorpusItem], out_dir: str,
                  commercial_only: bool = False) -> dict:
    """Write manifest.jsonl, manifest.csv and the dataset card to ``out_dir``."""
    selection = [it for it in items
                 if (it.is_sellable() if commercial_only
                     else it.state == ItemState.ACCEPTED)]
    write_jsonl(selection, os.path.join(out_dir, "manifest.jsonl"))
    write_csv_manifest(selection, os.path.join(out_dir, "manifest.csv"))
    write_dataset_card(selection, os.path.join(out_dir, "DATASET_CARD.md"))
    return summarise(selection)
