#!/usr/bin/env node
import { spawn, spawnSync } from "node:child_process";
import { existsSync, readFileSync, appendFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import os from "node:os";

const ENV_FILE = ".env.local";
const PORT = process.env.PORT ? Number(process.env.PORT) : 3000;
const URL_PATTERN = /(https:\/\/[a-z0-9-]+\.trycloudflare\.com)/;

function log(msg) {
  process.stdout.write(`\x1b[2m[quickstart]\x1b[0m ${msg}\n`);
}

function ensureAdminPassword() {
  let pw = process.env.ADMIN_PASSWORD;
  if (existsSync(ENV_FILE)) {
    const content = readFileSync(ENV_FILE, "utf8");
    const m = content.match(/^ADMIN_PASSWORD=(.+)$/m);
    if (m && m[1].trim()) pw = m[1].trim();
  }
  if (!pw || pw.length < 6) {
    pw = randomBytes(8).toString("base64url").slice(0, 12);
    appendFileSync(
      ENV_FILE,
      `\n# Generated by scripts/quickstart.mjs\nADMIN_PASSWORD=${pw}\n`,
    );
    log(`新しい ADMIN_PASSWORD を生成して ${ENV_FILE} に保存しました。`);
  }
  process.env.ADMIN_PASSWORD = pw;
  return pw;
}

function cloudflaredCmd() {
  const tryCmd = (cmd, args) => {
    const r = spawnSync(cmd, args ?? ["--version"], {
      stdio: "ignore",
      shell: true,
    });
    return r.status === 0;
  };
  if (tryCmd("cloudflared")) return { cmd: "cloudflared", argv: [] };
  if (tryCmd("npx", ["--no-install", "cloudflared", "--version"]))
    return { cmd: "npx", argv: ["--no-install", "cloudflared"] };
  return null;
}

function installInstructions() {
  const p = os.platform();
  if (p === "darwin") return "brew install cloudflared";
  if (p === "win32") return "winget install --id Cloudflare.cloudflared";
  return "curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared && chmod +x cloudflared && sudo mv cloudflared /usr/local/bin/";
}

function banner({ url, password, port }) {
  const ad = `${url}/admin`;
  const exp = `${url}/e/default`;
  const lines = [
    "",
    "\x1b[42;30m  Go-on Lab is live on your phone  \x1b[0m",
    "",
    `  \x1b[1m被験者用URL\x1b[0m   : \x1b[32m${exp}\x1b[0m`,
    `  \x1b[1m管理パネル\x1b[0m    : \x1b[36m${ad}\x1b[0m`,
    `  \x1b[1m管理パスワード\x1b[0m: \x1b[33m${password}\x1b[0m`,
    "",
    `  ローカル        : http://localhost:${port}`,
    "",
    "  停止: Ctrl+C",
    "",
  ];
  process.stdout.write(lines.join("\n") + "\n");
}

async function main() {
  const password = ensureAdminPassword();
  const cf = cloudflaredCmd();
  if (!cf) {
    console.error(
      "\n\x1b[31mcloudflared が見つかりません。\x1b[0m インストール手順:\n  " +
        installInstructions() +
        "\n",
    );
    process.exit(1);
  }

  log(`Next.js を起動します (port ${PORT})…`);
  const next = spawn("npm", ["run", "dev", "--", "--port", String(PORT)], {
    stdio: ["inherit", "inherit", "inherit"],
    env: { ...process.env, ADMIN_PASSWORD: password },
    shell: true,
  });

  const cleanup = () => {
    try {
      next.kill("SIGTERM");
    } catch {}
    try {
      tunnel?.kill("SIGTERM");
    } catch {}
  };
  process.on("SIGINT", () => {
    cleanup();
    process.exit(0);
  });
  process.on("SIGTERM", cleanup);

  await new Promise((r) => setTimeout(r, 4000));

  log(`Cloudflare Quick Tunnel を起動します…`);
  const tunnel = spawn(
    cf.cmd,
    [...cf.argv, "tunnel", "--url", `http://localhost:${PORT}`],
    { stdio: ["inherit", "pipe", "pipe"], shell: true },
  );

  let urlAnnounced = false;
  const handle = (chunk) => {
    const text = chunk.toString();
    process.stdout.write(text);
    if (!urlAnnounced) {
      const m = text.match(URL_PATTERN);
      if (m) {
        urlAnnounced = true;
        setTimeout(
          () => banner({ url: m[1], password, port: PORT }),
          400,
        );
      }
    }
  };
  tunnel.stdout?.on("data", handle);
  tunnel.stderr?.on("data", handle);

  tunnel.on("exit", (code) => {
    log(`cloudflared が終了 (code ${code}). Next.js も停止します。`);
    cleanup();
    process.exit(code ?? 0);
  });
  next.on("exit", (code) => {
    log(`Next.js が終了 (code ${code}). cloudflared も停止します。`);
    cleanup();
    process.exit(code ?? 0);
  });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
